### ISSUE TITLE
AppiumCommandExecutor: VTable failed, and 'Dispose' method lacks implementation

### ISSUE THREAD

**Issue by gamesguru** [appium/appium-dotnet-driver#217]
## The problem

After updating appium, node, and packages in visual studio I can no longer get the phone to connect.

## Environment

Appium 1.7.2
java 1.8.0_162
node 5.8.0
samsung J3 (6.0.1)
macOS and win10

## Details
Occurs at the constructor for the device driver (line 230 of testLogic.cs)

Source code: [appiumAndroidUnitTests.zip](https://github.com/appium/appium/files/1895236/appiumAndroidUnitTests.zip)

```
macOS
 ===============
  --Exception--
 ===============
4/10/2018 11:18:23 AM
appium-dotnet-driver, -2146233054
System.Collections.ListDictionaryInternal
VTable setup of type OpenQA.Selenium.Appium.Service.AppiumCommandExecutor failed


Void .ctor(Uri, ICapabilities)
  at OpenQA.Selenium.Appium.AppiumDriver`1[W]..ctor (System.Uri remoteAddress, OpenQA.Selenium.ICapabilities desiredCapabilities) [0x00000] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at OpenQA.Selenium.Appium.Android.AndroidDriver`1[W]..ctor (System.Uri remoteAddress, OpenQA.Selenium.Remote.DesiredCapabilities desiredCapabilities) [0x0000d] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at appiumUnitTests.testLogic.runTests (appiumUnitTests.Program+device de) [0x00846] in /Users/sjaroch/Desktop/repos/appiumandroidunittestscsharp/appiumUnitTests/testLogic.cs:230 
 ===================
  --End exception--
 ===================

 
 
 Windows
 ===============
  --Exception--
 ===============
4/10/2018 11:20:26 AM
appium-dotnet-driver, -2146233054
System.Collections.ListDictionaryInternal
Method 'Dispose' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'appium-dotnet-driver, Version=3.0.0.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.


Void .ctor(System.Uri, OpenQA.Selenium.ICapabilities, System.TimeSpan)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.Android.AndroidDriver`1..ctor(Uri remoteAddress, DesiredCapabilities desiredCapabilities)
   at appiumUnitTests.testLogic.runTests(device de) in C:\Users\sjaroch\Desktop\android-test-lib\appiumAndroidUnitTests\appiumUnitTests\testLogic.cs:line 230
 ===================
  --End exception--
 ===================
```

**Comment by gamesguru** [comment]
interesting, I'll try rolling it back.

Were you having issues with it connecting to the device consistently at all?  Maybe we were having this issue all along, and now they just save us from waiting the 60 second timeout?

**Comment by cmautosanity** [comment]
Hi,
I'm facing the same issue, where can I find the new selenium release (v3.11.2)?
In selenium download page I can see only - 3.11.1 version.
Thanks

**Comment by gr8viju** [comment]
You will need to get latest nuget package.

**Comment by ronjonesjr** [comment]
This seems to have reappeared in v3.13.0 no?

**Comment by RoakyWood** [comment]
I'm also seeing it in 3.13 with Appium 1.8.0

**Comment by wapatt** [comment]
I have the same problem with 3.13.1

**Comment by icvasa** [comment]
The same issue with 3.13.0/3.13.1 selenium.Webdriver

Exception: Message: System.TypeLoadException : Method 'Dispose' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'appium-dotnet-driver, Version=3.0.0.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by markleavesley** [comment]
Using Appium.WebDriver 4.0.0.1-beta is giving this: 

System.TypeLoadException: 'Method 'Dispose' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'appium-dotnet-driver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

I've been using Selenium (webdriver 3.13.1) for some desktop work in the same project without a hitch, I also have EasyRepro in the project..

Selenium 3.11.2 works.

**Comment by backmask** [comment]
As mentioned in https://github.com/SeleniumHQ/selenium/issues/6045, this breaking change is expected

**Comment by SamSamiGupta** [comment]
i still facing same error, can some one help me .

**Comment by gr8viju** [comment]
[FAST_Libs.zip](https://github.com/appium/appium-dotnet-driver/files/2194353/FAST_Libs.zip)


Hi, Could you please try using attached dll files and let me know. I am able to run my scripts smoothly with this. Unfortunately we cant update reference dlls easily in my project, and new dlls are not giving any additional benefits either.

**Comment by RoakyWood** [comment]
The Selenium people are saying that they made a known change that broke Appium and Appium has to catch up.

A similar error is crashing the click method in IE11 for IWebelement and they haven’t fixed that yet either.

It would be nice for the automated test community if someone from Appium could talk to someone from Selenium.

Peace


On Jul 13, 2018, at 6:23 PM, SamSamiGupta <notifications@github.com<mailto:notifications@github.com>> wrote:


i still facing same error, can some one help me .

**Comment by gamesguru** [comment]
This often happens with the C# client.

To save yourself some headaches either stick with an older (but still recent) version, like 3.12.x.  Or consider moving to the Java client.

**Comment by mykola-mokhnach** [comment]
...Or become dotnet client maintainer. Right now we [are looking](https://discuss.appium.io/t/wanted-dotnet-client-maintainer/22685) for one

**Comment by gamesguru** [comment]
That sounds lovely!  For a short-term solution I would suggest the Java client on iOS.

With Android there are other frameworks worth exploring, such as openatx python client for uiautomator2.

**Comment by RoakyWood** [comment]
Might I have the temerity to kindly inquire when might the fix could possibly be ready? 

Quoting the above-referenced release notes... 

_Reinstated ICommandExecutor descending from IDisposable. Now that the Appium project has implemented the methods required by an implementation of IDisposable, this change can be made upstream in the Selenium project. As this change has been rolled back once before to accommodate downstream projects, it will be incumbent upon them to update their libraries now, as it will not be rolled back again. In the case of Appium, this is merely awaiting a binary release_

RW

**Comment by gamesguru** [comment]
There is no fix he said they need a c# maintainer did you catch that?

I highly suggest using an old version of the selenium server in the meantime and posting results back

**Comment by RoakyWood** [comment]
Yes. I caught that. I intend to roll back. I assume you mean no fix is imminent.

On Jul 24, 2018, at 5:36 PM, gamesguru <notifications@github.com<mailto:notifications@github.com>> wrote:


There is no fix he said they need a c# maintainer did you catch that?

I highly suggest using an old version of the selenium server in the meantime and posting results back

**Comment by RoakyWood** [comment]
The condescension doesn’t merit a public response. The real issue is about taking care of your customers/User base.

In this case, the issue with clarified 31 days ago and it was first discovered 106 days ago, which is a lifetime in software.

Customers are not happy do we blame the customer?


On Jul 24, 2018, at 6:27 PM, gamesguru <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not with appium so i have no idea. it could be solved in 2 days or in 12 weeks, but trying out the different 3.11.x and 3.12.x selenium servers would take only minutes. And sharing your findings here would help others

One of the guys at my work has a conservative attitude about "not updating". He's not in the testing department, but I think what he says definitely applies to Appium in the case of its lesser maintained clients. You shouldn't be always rushing to upgrade just cause there's an update button flashing; staying put is perfectly safe too

**Comment by gamesguru** [comment]
I'm not with Appium, I opened this ticket because I had had it with them.

I can sympathize with your cause, but I won't take it personally if you ignore my suggestions.  Some of them may be radical, do openatx/uiautomator2 with Android, switch to the Java client for iOS.  I agree, they are radical, but they are still great suggestions you can discuss with your team.

If you're not comfortable with those, just downgrade the selenium server as recommended.  And don't launch some conspiracy at me holy cannoli, I'm just a guy who's bored and trying to help

**Comment by RoakyWood** [comment]
Let’s just leave it at that

On Jul 24, 2018, at 7:14 PM, gamesguru <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not with Appium, I opened this ticket because I had had it with them.

I can sympathize with your cause, but I won't take it personally if you ignore my suggestions. Some of them may be radical, do openatx/uiautomator2 with Android, switch to the Java client for iOS. I agree, they are radical, but they are still great suggestions you can discuss with your team.

If you're not comfortable with those, just downgrade the selenium server as recommended. And don't launch some conspiracy at me holy cannoli, I'm just a guy who's bored and trying to help

**Comment by RoakyWood** [comment]
Thanks, San, I’ll try it.
RW

On Jul 25, 2018, at 3:29 AM, Sam <notifications@github.com<mailto:notifications@github.com>> wrote:


Anyone who faces this bug, please try version 3.12.1, it works.

**Comment by gamesguru** [comment]
The 3.12.1 version for c# may throw an exception when assigning lists/collections of web elements, but for now it solves our problems.

You could also see a problem when code execution reaches the MultiTouch or Remote Selenium, or some other assembly that isn't used terribly often.  Try a different selenium server if you hit roadblocks

**Comment by SamSamiGupta** [comment]
If anyone can share there working code for AndroidDriver, it will be help.

**Comment by weylert** [comment]
Anyone found a way to resolve this without downgrading selenium?

**Comment by RoakyWood** [comment]
@weylert It looks like #218 has a pull request for a fix that will be in Selenium 3.14. It's not officially posted to the Selenium Downloads page yet.

**Comment by weylert** [comment]
Thanks for the info @RoakyWood !

**Comment by forki** [comment]
I can confirm that this is breaking and 3.12.1  works

**Comment by RoakyWood** [comment]
> I can confirm that this is breaking and 3.12.1  works

What versions of Appium and Selenium were breaking?

**Comment by forki** [comment]
Selenium 3.11.2 works. 3.14 does not

**Comment by RoakyWood** [comment]
To be fair, Selenium says downstream partners have to fix this, i.e., Appium. I have yet to see and Appium release that fixes this. Possibly they could keep the user community updated on progress. I ended up just creating a 'Rube Goldberg' native test on Xcode, executed from PowerShell to a MAC to run against an iOS device.

**Comment by akinsolb** [comment]
resolved by #218

**Comment by saigovindu** [comment]
In Selenium 3.12 is working but not in selenium 3.14

**Comment by akinsolb** [comment]
If you're upgrading the Selenium WebDriver to a greater version than what is in the release, then you should be wary of a difference in the packaged functionality. [The latest pre-release beta nuget](https://www.nuget.org/packages/Appium.WebDriver/4.0.0.2-beta) resolves this issue but may come with its own set of bugs. If that is the case, raise the issue as usual.

**Comment by ob1jedi** [comment]
I've downgraded to 3.12   :'(

**Comment by Dzingorang** [comment]
Anyone tested if issue still exists when using new Appium release and selenium webdriver higher than 3.12?

**Comment by VitaliiDolotov** [comment]
> Anyone tested if issue still exists when using new Appium release and selenium webdriver higher than 3.12?

Unfortunately issue is still exists...

**Comment by akinsolb** [comment]
@VitaliiDolotov @Dzingorang have you tried using the latest beta version? If you are using the latest beta version and still find this issue, please raise a new issue
